# Generated by Django 5.0.6 on 2024-05-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('email_id', models.EmailField(max_length=254)),
                ('account_id', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
                ('app_secret_token', models.CharField(max_length=50)),
                ('website', models.URLField(null=True)),
            ],
        ),
    ]
