# Generated by Django 4.2.8 on 2024-05-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_destination_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE'), ('CONNECT', 'CONNECT')], max_length=10),
        ),
    ]
