# Generated by Django 3.2.12 on 2024-05-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='headers',
            field=models.JSONField(default='ss'),
            preserve_default=False,
        ),
    ]
